# Generated by Django 5.0.2 on 2024-02-24 21:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.TextField(default='EMPTY')),
                ('blogId', models.TextField(default='EMPTY')),
            ],
        ),
    ]
