# Generated by Django 5.0.2 on 2024-03-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.TextField(default='bob'),
            preserve_default=False,
        ),
    ]
