services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    build: ./lvlgg_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/lvlgg_backend/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
  pgadmin:
    image: dpage/pgadmin4
    environment:
        PGADMIN_DEFAULT_EMAIL: niexin01@hotmail.com
        PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
  frontend:
    build: ./lvlgg_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./lvlgg_frontend:/app
    depends_on:
      - backend
    