# Generated by Django 5.0.2 on 2024-02-22 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_first_name_client_firstname_and_more'),
        ('account', '0003_rename_first_name_client_firstname_more'),
    ]

    operations = [
    ]
