# Generated by Django 5.0.2 on 2024-03-08 02:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
