FROM node:21-slim

# Set the working directory
WORKDIR /LvlUp.gg/lvlgg_frontend

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your application code
COPY . .

# Expose the port your React app runs on
EXPOSE 3000

# Command to start your React app
CMD ["npm", "start"]