# Generated by Django 4.2 on 2024-02-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_data_posted_blog_date_posted_alter_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.TextField(default='EMPTY'),
        ),
    ]
