name: Django CI

on:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["master", "develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        working-directory: ./lvlgg_backend
        run: |
          python -m pip install --upgrade pip
          python -m pip install django-cors-headers
          pip install -r requirements.txt

      - name: Django Testing
        working-directory: ./lvlgg_backend
        run: |
          python manage.py test
