name: Static Analysis Scan

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  Scan-Build:
    runs-on: ubuntu-latest
    steps:
    -  uses: actions/checkout@v3
       with:
        fetch-depth: 0
    -  name: Perform Scan
       uses: AppThreat/sast-scan-action@master
       with:
        type: "python"
        